<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAawktyc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAawktyc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAawktyc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAawktyc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAawktyc\appProdProjectContainer([
    'container.build_hash' => 'Aawktyc',
    'container.build_id' => 'e19ab71d',
    'container.build_time' => 1566251706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAawktyc');
